apple_library(
  name = 'one',
  exported_headers = ['one/one.h'],
  srcs = ['one/one.m'],
)

apple_library(
  name = 'parent',
  visibility = ['PUBLIC'],
  srcs = [ 'parent.swift' ],
  deps = [ ':one' ],
)

apple_binary(
  name = 'main',
  srcs = ['main.swift'],
  deps = [':parent'],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ],
)
